package com.lorbeer.randomland.domain;

public enum Baujahrklassen {

    VORKRIEGSBAU,
    NACHKRIEGSBAU,
    ERSTE_WAERMESCHUTZVERORDNUNG,
    ZWEITE_WAERMESCHUTZVERORDNUNG,
    DRITTE_WAERMESCHUTZVERORDNUNG,
    ERSTE_EINSPARVERORDNUNG,
    ZWEITE_EINSPARVERORDNUNG
}
